services:
  backend:
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver_plus 0.0.0.0:8000 --cert server.crt --key server.key"
