version: '3.9'

services:
  backend:
    container_name: backend
    environment:
      POSTGRES_HOST: db
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SUPERUSER_PASSWORD: admin123
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
      - django_logs:/app/logs
    depends_on:
      - db
    command: >
      sh -c "python manage.py migrate &&
             python manage.py createsuperuser --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: where2go
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - node-exporter
      - cadvisor
      - blackbox-exporter

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    privileged: true
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

  blackbox-exporter:
    image: prom/blackbox-exporter
    ports:
      - "9115:9115"

  process-exporter:
    image: ncabatoff/process-exporter
    volumes:
      - /proc:/host/proc:ro
      - ./monitoring/process-exporter:/config
    command:
      - --config.path=/config/config.yml
    ports:
      - "9256:9256"

  loki:
    image: grafana/loki
    volumes:
      - ./backend:/app
      - django_logs:/app/logs
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail
    volumes:
      - ./monitoring/promtail-config.yaml:/etc/promtail/promtail.yaml
      - ./backend:/app
      - django_logs:/app/logs
      - /tmp:/tmp
    command: -config.file=/etc/promtail/promtail.yaml
    depends_on:
      - loki

volumes:
  postgres_data:
  grafana_data:
  django_logs:

