# Generated by Django 4.2.19 on 2025-04-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Where2go', '0006_polloption_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
    ]
