# Generated by Django 4.2.19 on 2025-04-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Where2go', '0007_poll_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
