
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'process-exporter'
    static_configs:
      - targets: [ 'process-exporter:9256' ]

  - job_name: 'docker'
    static_configs:
      - targets: [ 'host.docker.internal:9323' ]

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://maps.api.2gis.ru/2.0/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'backend'
    static_configs:
      - targets: [ 'backend:8000' ]


