name: Build Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DGIS_API_KEY: ${{ secrets.DGIS_API_KEY }}
      REACT_APP_RECAPTCHA_SITE_KEY: ${{secrets.REACT_APP_RECAPTCHA_SITE_KEY}}
      REACT_APP_API_BASE_URL: ${{secrets.REACT_APP_API_BASE_URL}}
      
    steps:
      # Получение кода
      - name: Checkout repository
        uses: actions/checkout@v3

      # Установка Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend

      - name: Build frontend
        run: |
          if [ -f package.json ] && grep -q '"build"' package.json; then
            CI='' npm run build
          else
            echo "No build step defined in package.json"
          fi
        working-directory: frontend

      # Установка Python и pip-зависимостей
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
        
      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: backend

      # Запуск Django-команд
      - name: Migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate
        working-directory: backend

      - name: Show success message
        run: echo "Сборка завершена успешно."
