name: Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare SSL files
        run: |
          echo "${{ secrets.SSL_CRT_BASE64 }}" | base64 -d > server.crt
          echo "${{ secrets.SSL_KEY_BASE64 }}" | base64 -d > server.key

      - name: Set up Docker Compose
        run: |
          docker compose --version

      - name: Create .env file for backend
        run: echo "${{ secrets.BACKEND_ENV_CONTENTS }}" > backend/.env

      - name: Build and start containers
        run: |
          docker compose up -d --build

      - name: Wait for DB to be ready
        run: |
          echo "Waiting for PostgreSQL to start..."
          sleep 15

      - name: Run migrations
        run: docker compose run --rm backend python manage.py migrate

      - name: Stop containers
        run: docker compose down
