name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker-compose --version

      - name: Build and start containers
        run: |
          docker-compose up -d --build

      - name: Wait for DB to be ready
        run: |
          echo "Waiting for PostgreSQL to start..."
          sleep 15

      - name: Run migrations
        run: docker-compose run --rm backend python manage.py migrate

      - name: Stop containers
        run: docker-compose down
